# Generated by Django 6.0.4 on 2026-04-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('criticidad', models.CharField(max_length=20)),
            ],
        ),
    ]
