# Generated by Django 6.0.4 on 2026-04-29 00:49

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('criticidad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('predictivo', 'Predictivo')], default='preventivo', max_length=50)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=50)),
                ('costo', models.FloatField()),
                ('etiqueta', models.CharField(blank=True, choices=[('trimestral', 'Trimestral'), ('cuatrimestral', 'Cuatrimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('otro', 'Otro')], help_text='Periodicidad de este mantenimiento', max_length=20, null=True)),
                ('etiqueta_otro', models.CharField(blank=True, help_text='Descripción si etiqueta es "otro"', max_length=100, null=True)),
                ('fecha_proximo', models.DateField(blank=True, help_text='Fecha programada para el próximo mantenimiento', null=True)),
                ('etiqueta_proximo', models.CharField(blank=True, choices=[('trimestral', 'Trimestral'), ('cuatrimestral', 'Cuatrimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('otro', 'Otro')], help_text='Periodicidad del próximo mantenimiento', max_length=20, null=True)),
                ('etiqueta_proximo_otro', models.CharField(blank=True, help_text='Descripción si etiqueta_proximo es "otro"', max_length=100, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipo')),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tecnico')),
            ],
            options={
                'unique_together': {('equipo', 'tipo', 'fecha', 'descripcion', 'tecnico', 'estado', 'costo')},
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('certificado', 'Certificado de calibración'), ('orden', 'Orden de trabajo'), ('foto', 'Fotografía'), ('informe', 'Informe técnico'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('nombre', models.CharField(max_length=150)),
                ('archivo', models.FileField(upload_to=core.models.ruta_documento)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.CharField(blank=True, max_length=100)),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.mantenimiento')),
            ],
        ),
    ]
