# Generated by Django 6.0.4 on 2026-04-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mantenimiento',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='equipo',
            name='usos_mas',
            field=models.PositiveIntegerField(blank=True, help_text='Número de usos o mAs acumulados del equipo', null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='problema',
            field=models.TextField(blank=True, help_text='Problema o asunto reportado', null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='solucion',
            field=models.TextField(blank=True, help_text='Solución aplicada', null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='tipo_atencion',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], default='presencial', help_text='Modalidad de atención', max_length=20),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='tipo_otro',
            field=models.CharField(blank=True, help_text='Descripción si tipo es "otro"', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='tipo',
            field=models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('predictivo', 'Predictivo'), ('otro', 'Otro')], default='preventivo', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='mantenimiento',
            unique_together={('equipo', 'tipo', 'fecha', 'tecnico', 'estado', 'costo')},
        ),
    ]
