# Generated by Django 6.0.4 on 2026-04-25 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mantenimiento'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mantenimiento',
            unique_together={('equipo', 'tipo', 'fecha', 'descripcion', 'tecnico', 'estado', 'costo')},
        ),
    ]
