# Generated by Django 6.0.4 on 2026-04-29 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_mantenimiento_unique_together_equipo_usos_mas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del cliente o institución', max_length=150, unique=True)),
                ('ruc', models.CharField(blank=True, help_text='RUC o identificación fiscal', max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('contacto', models.CharField(blank=True, help_text='Persona de contacto', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['codigo'], 'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AddField(
            model_name='equipo',
            name='tubo_modelo',
            field=models.CharField(blank=True, help_text='Modelo del tubo de rayos X (dejar vacío si no aplica)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='tubo_serie',
            field=models.CharField(blank=True, help_text='Número de serie del tubo de rayos X (dejar vacío si no aplica)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente o institución propietaria del equipo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='core.cliente'),
        ),
    ]
