# Generated by Django 6.0.4 on 2026-04-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_alter_equipo_options_equipo_tubo_modelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='tipo_otro',
            field=models.CharField(blank=True, help_text='Especificar si el tipo es "Otro"', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo',
            field=models.CharField(choices=[('rayos_x', 'Rayos X'), ('tomografo', 'Tomógrafo (CT)'), ('resonancia', 'Resonancia Magnética (RM)'), ('ultrasonido', 'Ultrasonido / Ecógrafo'), ('mamografo', 'Mamógrafo'), ('fluoroscopio', 'Fluoroscopio'), ('densitometro', 'Densitómetro óseo'), ('arco_c', 'Arco en C'), ('angiografo', 'Angiógrafo'), ('pet_scan', 'PET / PET-CT'), ('monitor', 'Monitor de signos vitales'), ('ventilador', 'Ventilador mecánico'), ('desfibrilador', 'Desfibrilador / DEA'), ('electrocardiografo', 'Electrocardiógraf (ECG)'), ('oximetro', 'Oxímetro de pulso'), ('bomba_infusion', 'Bomba de infusión'), ('incubadora', 'Incubadora neonatal'), ('electrobisturi', 'Electrobisturí'), ('laser_medico', 'Láser médico'), ('arco_quirurgico', 'Arco quirúrgico'), ('analizador', 'Analizador / Autoanalizador'), ('centrifuga', 'Centrífuga'), ('microscopio', 'Microscopio'), ('espectrofotometro', 'Espectrofotómetro'), ('autoclave', 'Autoclave / Esterilizador'), ('ultrasonido_rehab', 'Ultrasonido terapéutico'), ('electroterapia', 'Electroterapia / TENS'), ('laser_rehab', 'Láser terapéutico'), ('rayos_x_dental', 'Rayos X dental'), ('unidad_dental', 'Unidad odontológica'), ('otro', 'Otro')], default='otro', help_text='Categoría del equipo biomédico', max_length=50),
        ),
    ]
