# Generated by Django 6.0.4 on 2026-04-25 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='tecnico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tecnico'),
        ),
    ]
