# Generated by Django 6.0.4 on 2026-04-30 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_equipo_tipo_otro_alter_equipo_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtareaPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipo', models.CharField(choices=[('rayos_x', 'Rayos X'), ('tomografo', 'Tomógrafo (CT)'), ('resonancia', 'Resonancia Magnética (RM)'), ('ultrasonido', 'Ultrasonido / Ecógrafo'), ('mamografo', 'Mamógrafo'), ('fluoroscopio', 'Fluoroscopio'), ('densitometro', 'Densitómetro óseo'), ('arco_c', 'Arco en C'), ('angiografo', 'Angiógrafo'), ('pet_scan', 'PET / PET-CT'), ('monitor', 'Monitor de signos vitales'), ('ventilador', 'Ventilador mecánico'), ('desfibrilador', 'Desfibrilador / DEA'), ('electrocardiografo', 'Electrocardiógraf (ECG)'), ('oximetro', 'Oxímetro de pulso'), ('bomba_infusion', 'Bomba de infusión'), ('incubadora', 'Incubadora neonatal'), ('electrobisturi', 'Electrobisturí'), ('laser_medico', 'Láser médico'), ('arco_quirurgico', 'Arco quirúrgico'), ('analizador', 'Analizador / Autoanalizador'), ('centrifuga', 'Centrífuga'), ('microscopio', 'Microscopio'), ('espectrofotometro', 'Espectrofotómetro'), ('autoclave', 'Autoclave / Esterilizador'), ('ultrasonido_rehab', 'Ultrasonido terapéutico'), ('electroterapia', 'Electroterapia / TENS'), ('laser_rehab', 'Láser terapéutico'), ('rayos_x_dental', 'Rayos X dental'), ('unidad_dental', 'Unidad odontológica'), ('otro', 'Otro')], help_text='Tipo de equipo al que aplica esta subtarea', max_length=50)),
                ('nombre', models.CharField(help_text='Descripción de la subtarea', max_length=200)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de aparición')),
                ('activa', models.BooleanField(default=True, help_text='Desactivar para ocultar sin borrar')),
            ],
            options={
                'verbose_name': 'Subtarea plantilla',
                'verbose_name_plural': 'Subtareas plantilla',
                'ordering': ['tipo_equipo', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='SubtareaEjecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completada', models.BooleanField(default=False)),
                ('nota', models.CharField(blank=True, help_text='Observación opcional sobre esta subtarea', max_length=300, null=True)),
                ('fecha_check', models.DateTimeField(blank=True, help_text='Cuándo se marcó como completada', null=True)),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtareas', to='core.mantenimiento')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='core.subtareaplantilla')),
            ],
            options={
                'verbose_name': 'Ejecución de subtarea',
                'verbose_name_plural': 'Ejecuciones de subtareas',
                'ordering': ['plantilla__orden', 'plantilla__nombre'],
                'unique_together': {('mantenimiento', 'plantilla')},
            },
        ),
    ]
