# Generated by Django 6.0.4 on 2026-04-25 21:03

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_mantenimiento_tecnico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('certificado', 'Certificado de calibración'), ('orden', 'Orden de trabajo'), ('foto', 'Fotografía'), ('informe', 'Informe técnico'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('nombre', models.CharField(max_length=150)),
                ('archivo', models.FileField(upload_to=core.models.ruta_documento)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.CharField(blank=True, max_length=100)),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.mantenimiento')),
            ],
        ),
    ]
