# Generated by Django 6.0.4 on 2026-05-01 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_subtareaplantilla_subtareaejecucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad o lugar donde se realiza el mantenimiento', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='programado',
            field=models.BooleanField(default=False, help_text='True = mantenimiento programado (periódico, generado por el sistema). False = no programado (imprevisto o correctivo puntual).'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='serie_programada',
            field=models.ForeignKey(blank=True, help_text='Primer mantenimiento de la serie (null si es el primero)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serie_hijos', to='core.mantenimiento'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='etiqueta',
            field=models.CharField(blank=True, choices=[('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('cuatrimestral', 'Cuatrimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('otro', 'Otro')], help_text='Periodicidad de este mantenimiento', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='etiqueta_proximo',
            field=models.CharField(blank=True, choices=[('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('cuatrimestral', 'Cuatrimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('otro', 'Otro')], help_text='Periodicidad del próximo mantenimiento', max_length=20, null=True),
        ),
    ]
