# Generated by Django 6.0.4 on 2026-04-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='etiqueta',
            field=models.CharField(blank=True, choices=[('trimestral', 'Trimestral'), ('cuatrimestral', 'Cuatrimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('otro', 'Otro')], help_text='Periodicidad de este mantenimiento', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='etiqueta_otro',
            field=models.CharField(blank=True, help_text='Descripción si etiqueta es "otro"', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='etiqueta_proximo',
            field=models.CharField(blank=True, choices=[('trimestral', 'Trimestral'), ('cuatrimestral', 'Cuatrimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('otro', 'Otro')], help_text='Periodicidad del próximo mantenimiento', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='etiqueta_proximo_otro',
            field=models.CharField(blank=True, help_text='Descripción si etiqueta_proximo es "otro"', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_proximo',
            field=models.DateField(blank=True, help_text='Fecha programada para el próximo mantenimiento', null=True),
        ),
    ]
