# Generated by Django 6.0.4 on 2026-05-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mantenimiento_ciudad_mantenimiento_programado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='codigo_error',
            field=models.CharField(blank=True, help_text='Código(s) de error reportados por el equipo. Puede ingresar varios separados por coma. También se detectan códigos mencionados en problema/solución.', max_length=200, null=True),
        ),
    ]
