# Generated by Django 6.0.4 on 2026-04-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mantenimiento_etiqueta_mantenimiento_etiqueta_otro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='tipo',
            field=models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('predictivo', 'Predictivo')], default='preventivo', max_length=50),
        ),
    ]
